# Generated by Django 6.0.4 on 2026-04-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brands_alter_car_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
