# Generated by Django 6.0.4 on 2026-04-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='car_value',
            new_name='cars_value',
        ),
    ]
