# Generated by Django 6.0.4 on 2026-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_car_value_carinventory_cars_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
